spring:
  exposed:
    show-sql: true
  datasource:
    driver-class-name: com.intersystems.jdbc.IRISDriver
    password: 'SYS'
    url: jdbc:IRIS://localhost:1972/USER/
    username: _SYSTEM
logging:
  level:
    org:
      springframework: info